---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environment_path: environments

platforms:
  - name: centos-7
    driver:
      box: centos/7

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: default
    run_list:
      - role[gibbon]

  - name: source
    provisioner:
      solo_rb:
        environment: source
    run_list:
      - role[gibbon]
